### ISSUE TITLE
some real world example?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [yuretz/FreeAwait#1]
asp.net minimal https://dotnetcoretutorials.com/2021/07/16/building-minimal-apis-in-net-6/?series ? todo list?

**Comment by yuretz** [comment]
It's in ASP.NET 5 (yet), but you can anyway take a look at [TodoBackend sample](https://github.com/yuretz/FreeAwait/tree/master/samples/TodoBackend) 😉

**Comment by yuretz** [comment]
Closed via #4.
The documentation is lagging behind a little, so I'm going to update it sometime soon so that the current version (0.5.0) is ready to be published to NuGet for the first time. 

Stay tuned and please feel free to open more issues with good ideas and suggestions. Thanks! 🙏
